# Generated by Django 5.0 on 2024-01-23 03:15

import category.models
import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=category.models.category_image_path, verbose_name='category_image')),
                ('bg_image', models.ImageField(upload_to=category.models.category_image_path, verbose_name='bg_image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=category.models.product_image_path, verbose_name='product_image')),
                ('price', models.PositiveSmallIntegerField(default=100, help_text='product_price_help_text', validators=[django.core.validators.MinValueValidator(100)], verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('page_title', models.CharField(help_text='page_title_help_text', max_length=60, verbose_name='page_title')),
                ('page_description', models.CharField(help_text='page_description_help_text', verbose_name='page_description')),
                ('name', models.CharField(help_text='category_name_help_text', max_length=100, unique=True, verbose_name='category_name')),
                ('description', models.TextField(help_text='category_description_help_text', verbose_name='category_description')),
                ('category_url', models.CharField(help_text='category_url_help_text', max_length=50, unique=True, verbose_name='category_url')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='category.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'category_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='product_name_help_text', max_length=100, verbose_name='product_name')),
                ('description', models.CharField(help_text='product_description_help_text', verbose_name='product_description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='category.product')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'category_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
