# Generated by Django 5.0 on 2024-01-23 03:15

import django.db.models.deletion
import parler.fields
import parler.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(help_text='twitter_help_text', verbose_name='twitter_url')),
                ('facebook', models.URLField(verbose_name='facebook_url')),
                ('instagram', models.URLField(verbose_name='instagram_url')),
                ('youtube', models.URLField(verbose_name='youtube_url')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(help_text='phone_help_text', max_length=16, region='YE', verbose_name='phone1')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='phone_help_text', max_length=16, null=True, region='YE', verbose_name='phone2')),
                ('email1', models.EmailField(max_length=254, verbose_name='email1')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email2')),
                ('work_from', models.TimeField(verbose_name='work_from')),
                ('work_to', models.TimeField(verbose_name='work_to')),
                ('bg_image', models.ImageField(upload_to='images/home/', verbose_name='bg_image')),
                ('about_us_bg_image', models.ImageField(upload_to='images/home/', verbose_name='about_us_bg_image')),
                ('our_goal_image', models.ImageField(upload_to='images/home/', verbose_name='our_goal_image')),
                ('our_vision_image', models.ImageField(upload_to='images/home/', verbose_name='our_vision_image')),
                ('our_message_image', models.ImageField(upload_to='images/home/', verbose_name='our_message_image')),
                ('our_categories_image', models.ImageField(upload_to='images/home/', verbose_name='our_categories_image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'home_page',
                'verbose_name_plural': 'home_page',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/branches/', verbose_name='branch_image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/agents/', verbose_name='agent_image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AgentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='agent_name_help_text', max_length=50, verbose_name='agent_name')),
                ('address', models.CharField(help_text='address_help_text', max_length=100, verbose_name='address')),
                ('description', models.TextField(help_text='agent_description_help_text', max_length=500, verbose_name='agent_description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.agent')),
            ],
            options={
                'verbose_name': 'agent Translation',
                'db_table': 'home_agent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BranchTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='branch_name_help_text', max_length=100, verbose_name='branch_name')),
                ('address', models.CharField(help_text='branch_address_help_text', max_length=255, verbose_name='address')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.branch')),
            ],
            options={
                'verbose_name': 'branch Translation',
                'db_table': 'home_branch_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('page_title', models.CharField(help_text='page_title_help_text', max_length=60, verbose_name='page_title')),
                ('page_description', models.CharField(help_text='page_description_help_text', verbose_name='page_description')),
                ('bg_description', models.TextField(help_text='bg_description_help_text', verbose_name='bg_description')),
                ('card1', models.CharField(help_text='cards_help_text', max_length=25, verbose_name='card1')),
                ('card2', models.CharField(help_text='cards_help_text', max_length=25, verbose_name='card2')),
                ('card3', models.CharField(help_text='cards_help_text', max_length=25, verbose_name='card3')),
                ('card4', models.CharField(help_text='cards_help_text', max_length=25, verbose_name='card4')),
                ('about_us', models.TextField(help_text='about_us_help_text', verbose_name='about_us')),
                ('our_goal_text', models.TextField(help_text='our_goal_help_text', verbose_name='our_goal_text')),
                ('our_vision_text', models.TextField(help_text='our_vision_help_text', verbose_name='our_vision_text')),
                ('our_message_text', models.TextField(help_text='our_message_help_text', verbose_name='our_message_text')),
                ('about_our_categories', models.TextField(help_text='about_our_categories_help_text', verbose_name='about_our_categories')),
                ('address', models.CharField(help_text='address_help_text', max_length=100, verbose_name='address')),
                ('work_days', models.CharField(help_text='work_days_help_text', max_length=25, verbose_name='work_days')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.section')),
            ],
            options={
                'verbose_name': 'home_page Translation',
                'db_table': 'home_section_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
