# Generated by Django 5.0 on 2024-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='twitter',
            field=models.URLField(verbose_name='twitter_url'),
        ),
    ]
